# -*- coding: utf-8 -*-
"""weather.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1jAwSZECo78njvz0iWZmEwMwbccrttuLk
"""

{"coord":{"lon":80.6167,"lat":16.5167},"weather":[{"id":721,"main":"Haze","description":"haze","icon":"50d"},{"id":500,"main":"Rain","description":"light rain","icon":"10d"}],"base":"stations","main":{"temp":309.12,"feels_like":316.12,"temp_min":309.12,"temp_max":309.12,"pressure":1002,"humidity":59},"visibility":5000,"wind":{"speed":3.09,"deg":320},"rain":{"1h":0.88},"clouds":{"all":75},"dt":1624363324,"sys":{"type":1,"id":9207,"country":"IN","sunrise":1624320367,"sunset":1624367569},"timezone":19800,"id":6571806,"name":"Vijayawada","cod":200}